default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: db

development:
  <<: *default
  database: sample_db_development

production:
  primary: &primary_production
    <<: *default
    database: sample_db_production
    username: app
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: sample_db_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sample_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sample_production_cable
    migrations_paths: db/cable_migrate
