- name: Setup database config for CI
  run: |
    cat > config/database.yml << 'EOF'
    default: &default
      adapter: mysql2
      encoding: utf8mb4
      pool: 5
      username: user
      password: password
      host: 127.0.0.1

    test:
      <<: *default
      database: sample_db_test
    EOF